### PR TITLE
[Refactor] LightningModule and scripts folder

### PR DESCRIPTION
**Pull request by DavianYang**
### What does this PR introduce?

I like to separate the lightning module folder apart from model folder. Being model folder alone is more convenient when we set this repo to be a package. This would make you easily call the model from packages.

And the examples folder is where the run file be organized. What do you think?

### CODE REVIEW

**Comment by ydcjeff** [comment]
So, in model folder, there will only be models implemented with LightningModule and running files in examples folder?

**Comment by DavianYang** [comment]
Exactly

**Comment by ydcjeff** [comment]
I would like to change examples to scripts

**Comment by DavianYang** [comment]
Yep that's great, too

**Comment by DavianYang** [comment]
Shall I merge now

**Comment by ydcjeff** [comment]
Before that, should we put `s` in the folders which don't include `s`?
like models, loggers

**Comment by DavianYang** [comment]
Okie i will rename that

**Comment by DavianYang** [comment]
I think, there will be some conflicts if I changed in neuro_model

**Comment by ydcjeff** [comment]
> I think, there will be some conflicts if I changed in neuro_model

will need to rename all of them in a separate PR

**Comment by DavianYang** [comment]
Yep, there will be refactor PR for that in neuro_model

**Pull request merged**
